### ISSUE TITLE
Bug: cannot delete user or group

### ISSUE THREAD

**Issue by YEthYuan** [scalableinternetservices/Hydra#34]
When clicking the button in user's/group's profile page, the destroy action cannot be executed as expected.

**Comment by YEthYuan** [comment]
![image](https://user-images.githubusercontent.com/56443653/200189585-3ee99eb0-ec45-4970-b718-f29913870c13.png)

**Comment by YEthYuan** [comment]
The problem might caused by the undefined foreign key

**Comment by Mrxxxx-1** [comment]
![image](https://user-images.githubusercontent.com/81565382/201179119-912524f3-64f6-4f4c-9c6b-d853748661c0.png)
https://guides.rubyonrails.org/getting_started.html#deleting-associated-objects
This might help
