### ISSUE TITLE
Feat: Create User Model

### ISSUE THREAD

**Issue by YEthYuan** [scalableinternetservices/Hydra#7]
As discussed in our last weekly sync, a user model should contain the following properties: 

- User
  - UserID: int
  - Username: string
  - password_digest: string
  - Email: string
  - About: text
  - Avatar: int (pic#)
  - Status: {online, offline, invisible, busy}

Note that we can add new properties for the User model in the future, so feel free to implement a initial model first.

**Comment by AndyCheng2** [comment]
If you need use the session to trace the user login logout, please make sure change the Password: string=>password_digest: string. By doing this we can use the has_secure_password function to develop session. More details can see my previous feature commit in https://github.com/YEthYuan/UCSBCS291AProject3/commit/60aac366a48a276d26ee703efad0dfc2eb63eae5

**Comment by YEthYuan** [comment]
> @YEthYuan If you need use the session to trace the user login logout, please make sure change the Password: string=>password_digest: string. By doing this we can use the has_secure_password function to develop session. More details can see my previous feature commit in [YEthYuan/UCSBCS291AProject3@60aac36](https://github.com/YEthYuan/UCSBCS291AProject3/commit/60aac366a48a276d26ee703efad0dfc2eb63eae5)

Thanks for your response! I just modified its class.
